<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRGTEST" Id="{cb0dada2-790f-48b3-8702-fc17bd7e66f5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRGTEST
VAR
	sequencer_test : FB_Sequencer_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>