<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TESTPRG" Id="{cb0dada2-790f-48b3-8702-fc17bd7e66f5}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no-analysis'}
PROGRAM TESTPRG
VAR
    sequencerTest : Sequencer_Test;
    stepManagerTest : StepManagerBasic_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Copyright (c) 2024 Loupe (https://loupe.team), provided under the MIT License.

TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>